In [19]:
import pandas as pd
import requests
import json

In [20]:
symbol = '2330'

### TWSE

In [21]:
twse_api_url = 'https://openapi.twse.com.tw/v1/exchangeReport/STOCK_DAY_ALL'
res = requests.get(twse_api_url)
data = json.loads(res.text)

twse_df = pd.DataFrame(data)

twse_df

,Code,Name,TradeVolume,TradeValue,OpeningPrice,HighestPrice,LowestPrice,ClosingPrice,Change,Transaction
0,0050,元大台灣50,14311332,2620276842,183.10,184.10,182.45,182.45,2.3000,16087
1,0051,元大中型100,47993,3870924,80.95,80.95,80.20,80.35,-0.2500,284
2,0052,富邦科技,719628,128609934,180.00,180.00,177.80,177.80,1.8500,1233
3,0053,元大電子,18214,1785055,97.20,98.75,97.20,97.75,1.3000,142
4,0055,元大MSCI金融,185273,5382220,29.01,29.20,29.01,29.04,0.0500,263
...,...,...,...,...,...,...,...,...,...,...
1250,9944,新麗,127455,2573894,20.10,20.30,20.10,20.25,0.0500,215
1251,9945,潤泰新,25455283,1205535610,48.45,48.60,46.30,47.50,-1.7500,17945
1252,9946,三發地產,3318845,100416055,30.80,30.95,29.70,30.90,-2.1000,2004
1253,9955,佳龍,1357583,49492777,36.55,36.90,36.15,36.30,0.3500,931
1254,9958,世紀鋼,26598234,6467597994,240.00,250.50,234.50,241.50,7.0000,29946

In [22]:
twse_df[twse_df['Code'] == symbol]

,Code,Name,TradeVolume,TradeValue,OpeningPrice,HighestPrice,LowestPrice,ClosingPrice,Change,Transaction
480,2330,台積電,66762167,65105344444,981.00,982.00,971.00,973.00,13.0000,67911

### Yahoo

In [23]:
import yfinance as yf

In [24]:
yahoo_data = yf.download(f'{symbol}.TW', period='1d')

yahoo_data

[*********************100%***********************]  1 of 1 completed

             Open   High    Low  Close  Adj Close    Volume
Date
2024-09-20  981.0  982.0  971.0  973.0      973.0  60133709